data:
  data_dir: 'C:\Users\mcant\Desktop\Chest_xray_data\Chest X-ray images\chest_xray\chest_xray'
  batch_size: 32
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  classes:
    - 'NORMAL'
    - 'PNEUMONIA'
  seed: 42

model:
  name: 'resnet18'
  pretrained: True

training:
  seed: 42
  learning_rate: 0.01
  num_epochs: 15
  step_size: 10
  gamma: 0.1
  checkpoint_dir: 'C:\Users\mcant\Desktop\DeepLearning_RESNET_Without_Augmentation\Resnet_withoutAugmentation_Kfold_1\checkpoints'
  k_fold: 5  # Number of folds for k-fold cross-validation
