data:
  data_dir: 'E:\DL_Project_Data\archive\chest_xray\chest_xray'
  batch_size: 24
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  classes:
    - 'NORMAL'
    - 'PNEUMONIA'
  image_size: 224  # Ensure this line exists

model:
  name: 'resnet18'
  pretrained: 'True'

training:
  seed: 42
  learning_rate: 0.0001
  num_epochs: 15
  step_size: 10
  gamma: 0.1
  checkpoint_dir: 'E:\deep_learning_project\Resnet_Data_Augmentation\Resnet_kfold_hypertunning_1\checkpoints'
